server:
  port: 5478

spring:
  application:
    name: cloud-jarproduce-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: admin_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://cloud-admin-service
          predicates:
            - Path=/user/** # 断言，路径相匹配的进行路由
            #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
#        - id: admin_route2
#          uri: lb://cloud-admin-service
#          predicates:
#            - Path=/user/selectUser/** #断言,路径相匹配的进行路由
#eureka:
#  instance:
#    hostname: cloud-gateway-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8001/eureka
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 不注册自己
    register-with-eureka: true
    # 表示自己是注册中心，不用检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka