server:
  port: 8010

spring:
  application:
    name: cloud-admin-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudjar?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root


eureka:
  client:
    # 注册
    register-with-eureka: true
    # 注册中心，检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configLocation: classpath:mybatis.xml
  type-aliases-package: com.cloud.common.entities